version: '{build}'
pull_requests:
  do_not_increment_build_number: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: 8R/tSu8wvwudMRGt8Ngxhyh9qQVebOLLZSZGmLGs711/wF1PzK4PEEVYCjR/lt2l
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\build.ps1
after_build:
- ps: .\coverage.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: PhzvKEzboYRGqGP1b9vHQIYr7yma8Aoadz8X7Fh3K+3/AbSu20BCeK3wvvgdQ0Co
  on:
    branch: master
    appveyor_repo_tag: true
