version: '{build}'
pull_requests:
  do_not_increment_build_number: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: 8ypKHp5Q5wUFaul/0dkyVBxA6bmt9/7Sl/+hHSTkCZlaM5+tmzykSq7QpzHg9wML
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\build.ps1
after_build:
- ps: .\set-debug-type.ps1
- ps: .\coverage.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: PhzvKEzboYRGqGP1b9vHQIYr7yma8Aoadz8X7Fh3K+3/AbSu20BCeK3wvvgdQ0Co
  on:
    branch: master
    appveyor_repo_tag: true
